### ISSUE TITLE
Is it possible to use webRTC audio streams with the mixer?

### ISSUE THREAD

**Issue by mgw-sbex** [danbovey/wam#5]
Hi Dan, great repo/project! Congrats. We are looking for a mixer like yours that can also use webRTC audio streams in the browser to be part of the inputs. Is it possible? Thank you!

**Comment by danbovey** [comment]
Hi Michael! I'm not up to date on the APIs for webRTC but if there's a method to pipe the audio input from a webRTC stream to the correct Web Audio APIs, it may be possible to use the same ideas in this project to calculate the BPM of the buffered audio input. Good luck!
